### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by schmidtp1** [gbr1/sengi#1]
@gbr1, where can I get the PCB? Can you recommend any place to order?

**Comment by gbr1** [comment]
I often use  [ALL PCB](https://www.allpcb.com/?campaignid=1997729204&adgroupid=72678298713&feeditemid=&targetid=aud-758015688410:kwd-326584813899&loc_physical_ms=9050577&matchtype=e&network=g&device=c&devicemodel=&creative=353879586367&keyword=allpcb&placement=&target=&adposition=1t1&gclid=CjwKCAiAh5_uBRA5EiwASW3IajCcBxEG8sb-PUrILut7G6OWeFsyfURbxAboho00UJGm8LylwQfNuhoCPr8QAvD_BwE).

I think that for cheap PCBs are all the same about quality, so check also [PCBway](https://www.pcbway.com/?gw1&campaignid=172480651&adgroupid=8787904531&feeditemid=&targetid=kwd-96217560494&loc_physical_ms=9050577&matchtype=p&network=g&device=c&devicemodel=&creative=377957049820&keyword=pcbway&placement=&target=&adposition=1t3&gclid=CjwKCAiAh5_uBRA5EiwASW3Iagy9WLCiHrQAQD7B3j7584qsAB1npoWM39hD4E6VoKsRbS4YWXlV9BoCjfgQAvD_BwE) and [JCLPCB](https://jlcpcb.com/)
